#!/bin/bash

echo "========================================="
echo "  UPLOAD THESE FILES TO YOUR SERVER"
echo "========================================="
echo ""
echo "Location: /Applications/MAMP/htdocs/hooknhunt/mantine/dist/"
echo ""
echo "FILES TO UPLOAD:"
echo "  1. index.html"
echo "  2. assets/index-G982CtGF.js  ← NEW FILE (embeds quotes)"
echo "  3. assets/index-BopuL_0p.css"
echo "  4. .htaccess"
echo ""
echo "FILES TO DELETE FROM SERVER:"
echo "  ❌ assets/index-D2QpjtUA.js  ← OLD FILE (causes error)"
echo "  ❌ registerSW.js"
echo "  ❌ sw.js"
echo "  ❌ workbox-*.js"
echo ""
echo "========================================="
echo "  AFTER UPLOAD:"
echo "========================================="
echo "  1. Clear browser cache (Ctrl+Shift+R)"
echo "  2. Hard refresh page"
echo "  3. Error will be GONE"
echo ""
echo "========================================="
