<?php

namespace Database\Seeders;

use App\Models\ProductVariant;
use Illuminate\Database\Seeder;

class ProductVariantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $variants = [
            // Professional Carbon Fiber Spinning Rod (Product ID: 1) - 3 variants
            [
                'product_id' => 1,
                'sku' => 'HHCFSR-7M-ML',
                'landed_cost' => 85,
                'retail_name' => 'Carbon Fiber Spinning Rod 7ft Medium-Light',
                'retail_price' => 280,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Carbon Fiber Spinning Rod 7ft ML Wholesale',
                'wholesale_price' => 220,
                'daraz_name' => 'Professional Spinning Rod 7ft ML',
                'daraz_price' => 350,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/4F46E5/FFFFFF?text=7ft+ML',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'sku' => 'HHCFSR-7M-M',
                'landed_cost' => 90,
                'retail_name' => 'Carbon Fiber Spinning Rod 7ft Medium',
                'retail_price' => 300,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Carbon Fiber Spinning Rod 7ft M Wholesale',
                'wholesale_price' => 240,
                'daraz_name' => 'Professional Spinning Rod 7ft M',
                'daraz_price' => 380,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/4F46E5/FFFFFF?text=7ft+M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 1,
                'sku' => 'HHCFSR-8M-MH',
                'landed_cost' => 95,
                'retail_name' => 'Carbon Fiber Spinning Rod 8ft Medium-Heavy',
                'retail_price' => 320,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Carbon Fiber Spinning Rod 8ft MH Wholesale',
                'wholesale_price' => 260,
                'daraz_name' => 'Professional Spinning Rod 8ft MH',
                'daraz_price' => 420,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/4F46E5/FFFFFF?text=8ft+MH',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Telescopic Travel Fishing Rod (Product ID: 2) - 2 variants
            [
                'product_id' => 2,
                'sku' => 'HHTTR-5.5M-ML',
                'landed_cost' => 45,
                'retail_name' => 'Telescopic Travel Rod 5.5ft Medium-Light',
                'retail_price' => 180,
                'moq_wholesale' => 10,
                'wholesale_name' => 'Telescopic Travel Rod 5.5ft ML Wholesale',
                'wholesale_price' => 140,
                'daraz_name' => 'Travel Telescopic Rod 5.5ft ML',
                'daraz_price' => 230,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/10B981/FFFFFF?text=5.5ft+ML',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 2,
                'sku' => 'HHTTR-6M-M',
                'landed_cost' => 50,
                'retail_name' => 'Telescopic Travel Rod 6ft Medium',
                'retail_price' => 200,
                'moq_wholesale' => 10,
                'wholesale_name' => 'Telescopic Travel Rod 6ft M Wholesale',
                'wholesale_price' => 160,
                'daraz_name' => 'Travel Telescopic Rod 6ft M',
                'daraz_price' => 260,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/10B981/FFFFFF?text=6ft+M',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Heavy Duty Casting Rod (Product ID: 3) - 2 variants
            [
                'product_id' => 3,
                'sku' => 'SH-HDCR-8M-H',
                'landed_cost' => 120,
                'retail_name' => 'Heavy Duty Casting Rod 8ft Heavy',
                'retail_price' => 450,
                'moq_wholesale' => 3,
                'wholesale_name' => 'Heavy Duty Casting Rod 8ft H Wholesale',
                'wholesale_price' => 380,
                'daraz_name' => 'Big Game Casting Rod 8ft Heavy',
                'daraz_price' => 580,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/F59E0B/FFFFFF?text=8ft+H',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 3,
                'sku' => 'SH-HDCR-9M-XH',
                'landed_cost' => 130,
                'retail_name' => 'Heavy Duty Casting Rod 9ft Extra-Heavy',
                'retail_price' => 500,
                'moq_wholesale' => 3,
                'wholesale_name' => 'Heavy Duty Casting Rod 9ft XH Wholesale',
                'wholesale_price' => 420,
                'daraz_name' => 'Big Game Casting Rod 9ft Extra-Heavy',
                'daraz_price' => 650,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/F59E0B/FFFFFF?text=9ft+XH',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Spinning Fishing Reel (Product ID: 4) - 3 variants
            [
                'product_id' => 4,
                'sku' => 'HH-SFR-2500',
                'landed_cost' => 40,
                'retail_name' => 'Spinning Fishing Reel 2500 Size',
                'retail_price' => 220,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Spinning Reel 2500 Wholesale',
                'wholesale_price' => 180,
                'daraz_name' => 'Advanced Spinning Reel 2500',
                'daraz_price' => 280,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/EF4444/FFFFFF?text=2500',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'sku' => 'HH-SFR-3000',
                'landed_cost' => 45,
                'retail_name' => 'Spinning Fishing Reel 3000 Size',
                'retail_price' => 250,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Spinning Reel 3000 Wholesale',
                'wholesale_price' => 200,
                'daraz_name' => 'Advanced Spinning Reel 3000',
                'daraz_price' => 320,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/EF4444/FFFFFF?text=3000',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 4,
                'sku' => 'HH-SFR-4000',
                'landed_cost' => 50,
                'retail_name' => 'Spinning Fishing Reel 4000 Size',
                'retail_price' => 280,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Spinning Reel 4000 Wholesale',
                'wholesale_price' => 220,
                'daraz_name' => 'Advanced Spinning Reel 4000',
                'daraz_price' => 360,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/EF4444/FFFFFF?text=4000',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Baitcasting Reel Pro (Product ID: 5) - 2 variants
            [
                'product_id' => 5,
                'sku' => 'DW-BCP-150',
                'landed_cost' => 80,
                'retail_name' => 'Baitcasting Reel Pro 150 Size',
                'retail_price' => 380,
                'moq_wholesale' => 3,
                'wholesale_name' => 'Baitcasting Reel Pro 150 Wholesale',
                'wholesale_price' => 320,
                'daraz_name' => 'Professional Baitcasting Reel 150',
                'daraz_price' => 480,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/8B5CF6/FFFFFF?text=150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 5,
                'sku' => 'DW-BCP-200',
                'landed_cost' => 90,
                'retail_name' => 'Baitcasting Reel Pro 200 Size',
                'retail_price' => 420,
                'moq_wholesale' => 3,
                'wholesale_name' => 'Baitcasting Reel Pro 200 Wholesale',
                'wholesale_price' => 360,
                'daraz_name' => 'Professional Baitcasting Reel 200',
                'daraz_price' => 540,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/8B5CF6/FFFFFF?text=200',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Monofilament Fishing Line (Product ID: 6) - 4 variants
            [
                'product_id' => 6,
                'sku' => 'HH-MFL-8LB-300',
                'landed_cost' => 8,
                'retail_name' => 'Monofilament Line 8lb Test 300 yards',
                'retail_price' => 45,
                'moq_wholesale' => 20,
                'wholesale_name' => 'Monofilament Line 8lb Wholesale',
                'wholesale_price' => 35,
                'daraz_name' => 'Fishing Line Monofilament 8lb',
                'daraz_price' => 60,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/06B6D4/FFFFFF?text=8lb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'sku' => 'HH-MFL-10LB-300',
                'landed_cost' => 9,
                'retail_name' => 'Monofilament Line 10lb Test 300 yards',
                'retail_price' => 50,
                'moq_wholesale' => 20,
                'wholesale_name' => 'Monofilament Line 10lb Wholesale',
                'wholesale_price' => 40,
                'daraz_name' => 'Fishing Line Monofilament 10lb',
                'daraz_price' => 70,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/06B6D4/FFFFFF?text=10lb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'sku' => 'HH-MFL-12LB-300',
                'landed_cost' => 10,
                'retail_name' => 'Monofilament Line 12lb Test 300 yards',
                'retail_price' => 55,
                'moq_wholesale' => 20,
                'wholesale_name' => 'Monofilament Line 12lb Wholesale',
                'wholesale_price' => 45,
                'daraz_name' => 'Fishing Line Monofilament 12lb',
                'daraz_price' => 75,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/06B6D4/FFFFFF?text=12lb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 6,
                'sku' => 'HH-MFL-15LB-300',
                'landed_cost' => 12,
                'retail_name' => 'Monofilament Line 15lb Test 300 yards',
                'retail_price' => 65,
                'moq_wholesale' => 20,
                'wholesale_name' => 'Monofilament Line 15lb Wholesale',
                'wholesale_price' => 55,
                'daraz_name' => 'Fishing Line Monofilament 15lb',
                'daraz_price' => 85,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/06B6D4/FFFFFF?text=15lb',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Braided Fishing Line (Product ID: 7) - 3 variants
            [
                'product_id' => 7,
                'sku' => 'SH-BFL-20LB-150',
                'landed_cost' => 15,
                'retail_name' => 'Braided Line 20lb Test 150 yards',
                'retail_price' => 80,
                'moq_wholesale' => 15,
                'wholesale_name' => 'Braided Line 20lb Wholesale',
                'wholesale_price' => 70,
                'daraz_name' => 'Super Braid Fishing Line 20lb',
                'daraz_price' => 100,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/84CC16/FFFFFF?text=20lb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'sku' => 'SH-BFL-30LB-150',
                'landed_cost' => 18,
                'retail_name' => 'Braided Line 30lb Test 150 yards',
                'retail_price' => 95,
                'moq_wholesale' => 15,
                'wholesale_name' => 'Braided Line 30lb Wholesale',
                'wholesale_price' => 85,
                'daraz_name' => 'Super Braid Fishing Line 30lb',
                'daraz_price' => 120,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/84CC16/FFFFFF?text=30lb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 7,
                'sku' => 'SH-BFL-50LB-150',
                'landed_cost' => 22,
                'retail_name' => 'Braided Line 50lb Test 150 yards',
                'retail_price' => 115,
                'moq_wholesale' => 15,
                'wholesale_name' => 'Braided Line 50lb Wholesale',
                'wholesale_price' => 105,
                'daraz_name' => 'Super Braid Fishing Line 50lb',
                'daraz_price' => 150,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/84CC16/FFFFFF?text=50lb',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Fluorocarbon Leader Line (Product ID: 8) - 2 variants
            [
                'product_id' => 8,
                'sku' => 'DW-FCL-12LB-100',
                'landed_cost' => 12,
                'retail_name' => 'Fluorocarbon Leader 12lb Test 100 yards',
                'retail_price' => 90,
                'moq_wholesale' => 10,
                'wholesale_name' => 'Fluorocarbon Leader 12lb Wholesale',
                'wholesale_price' => 80,
                'daraz_name' => 'Invisible Fluorocarbon Leader 12lb',
                'daraz_price' => 115,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/F97316/FFFFFF?text=12lb',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 8,
                'sku' => 'DW-FCL-20LB-100',
                'landed_cost' => 16,
                'retail_name' => 'Fluorocarbon Leader 20lb Test 100 yards',
                'retail_price' => 110,
                'moq_wholesale' => 10,
                'wholesale_name' => 'Fluorocarbon Leader 20lb Wholesale',
                'wholesale_price' => 100,
                'daraz_name' => 'Invisible Fluorocarbon Leader 20lb',
                'daraz_price' => 140,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/F97316/FFFFFF?text=20lb',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Premium Fishing Hooks Set (Product ID: 9) - 1 variant (single SKU)
            [
                'product_id' => 9,
                'sku' => 'HH-PFHS-50PCS',
                'landed_cost' => 25,
                'retail_name' => 'Premium Fishing Hooks Set 50 pieces',
                'retail_price' => 150,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Premium Hooks Set 50pcs Wholesale',
                'wholesale_price' => 120,
                'daraz_name' => 'Complete Fishing Hooks Kit 50 pieces',
                'daraz_price' => 190,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/EC4899/FFFFFF?text=50+Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Swivels and Snap Clips Set (Product ID: 10) - 1 variant (single SKU)
            [
                'product_id' => 10,
                'sku' => 'PN-SSCS-100PCS',
                'landed_cost' => 20,
                'retail_name' => 'Swivels Snap Clips Set 100 pieces',
                'retail_price' => 120,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Swivels Snap Clips 100pcs Wholesale',
                'wholesale_price' => 95,
                'daraz_name' => 'Complete Swivels Kit 100 pieces',
                'daraz_price' => 155,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/14B8A6/FFFFFF?text=100+Pcs',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Hard Plastic Lure Set (Product ID: 11) - 2 variants
            [
                'product_id' => 11,
                'sku' => 'HH-HPLS-MED-12',
                'landed_cost' => 35,
                'retail_name' => 'Hard Plastic Lure Set Medium 12 pieces',
                'retail_price' => 250,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Hard Lures Medium 12pcs Wholesale',
                'wholesale_price' => 200,
                'daraz_name' => 'Professional Lure Set Medium 12 pieces',
                'daraz_price' => 320,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/9333EA/FFFFFF?text=Medium+12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 11,
                'sku' => 'HH-HPLS-LRG-12',
                'landed_cost' => 40,
                'retail_name' => 'Hard Plastic Lure Set Large 12 pieces',
                'retail_price' => 280,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Hard Lures Large 12pcs Wholesale',
                'wholesale_price' => 230,
                'daraz_name' => 'Professional Lure Set Large 12 pieces',
                'daraz_price' => 360,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/9333EA/FFFFFF?text=Large+12',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Soft Plastic Worms (Product ID: 12) - 2 variants
            [
                'product_id' => 12,
                'sku' => 'AG-SPW-6IN-20',
                'landed_cost' => 15,
                'retail_name' => 'Soft Plastic Worms 6 inch 20 pieces',
                'retail_price' => 180,
                'moq_wholesale' => 10,
                'wholesale_name' => 'Soft Worms 6in 20pcs Wholesale',
                'wholesale_price' => 150,
                'daraz_name' => 'Scented Plastic Worms 6 inch 20 pieces',
                'daraz_price' => 230,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/059669/FFFFFF?text=6in+20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'product_id' => 12,
                'sku' => 'AG-SPW-8IN-15',
                'landed_cost' => 18,
                'retail_name' => 'Soft Plastic Worms 8 inch 15 pieces',
                'retail_price' => 200,
                'moq_wholesale' => 10,
                'wholesale_name' => 'Soft Worms 8in 15pcs Wholesale',
                'wholesale_price' => 170,
                'daraz_name' => 'Scented Plastic Worms 8 inch 15 pieces',
                'daraz_price' => 260,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/059669/FFFFFF?text=8in+15',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Fishing Tackle Box (Product ID: 13) - 1 variant (single SKU)
            [
                'product_id' => 13,
                'sku' => 'HH-FTB-14X8',
                'landed_cost' => 60,
                'retail_name' => 'Fishing Tackle Box 14" x 8"',
                'retail_price' => 350,
                'moq_wholesale' => 3,
                'wholesale_name' => 'Tackle Box 14x8 Wholesale',
                'wholesale_price' => 300,
                'daraz_name' => 'Professional Tackle Box Large',
                'daraz_price' => 450,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/DC2626/FFFFFF?text=14x8',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Fishing Pliers Tool (Product ID: 14) - 1 variant (single SKU)
            [
                'product_id' => 14,
                'sku' => 'SH-FPT-6.5IN',
                'landed_cost' => 45,
                'retail_name' => 'Fishing Pliers Tool 6.5 inch',
                'retail_price' => 280,
                'moq_wholesale' => 5,
                'wholesale_name' => 'Fishing Pliers 6.5in Wholesale',
                'wholesale_price' => 240,
                'daraz_name' => 'Multi Tool Fishing Pliers 6.5 inch',
                'daraz_price' => 360,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/6366F1/FFFFFF?text=6.5in',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Fishing Backpack (Product ID: 15) - 1 variant (single SKU)
            [
                'product_id' => 15,
                'sku' => 'HH-FBP-30L',
                'landed_cost' => 55,
                'retail_name' => 'Fishing Backpack 30 liters',
                'retail_price' => 320,
                'moq_wholesale' => 3,
                'wholesale_name' => 'Fishing Backpack 30L Wholesale',
                'wholesale_price' => 280,
                'daraz_name' => 'Fishing Bag with Rod Holders 30L',
                'daraz_price' => 420,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/8B5CF6/FFFFFF?text=30L',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Fish Finder Portable (Product ID: 16) - 1 variant (single SKU)
            [
                'product_id' => 16,
                'sku' => 'SH-FFP-100FT',
                'landed_cost' => 80,
                'retail_name' => 'Fish Finder Portable 100 feet depth',
                'retail_price' => 550,
                'moq_wholesale' => 2,
                'wholesale_name' => 'Fish Finder 100ft Wholesale',
                'wholesale_price' => 480,
                'daraz_name' => 'Portable Fish Detector 100 feet range',
                'daraz_price' => 700,
                'variant_thumbnail_url' => 'https://via.placeholder.com/400x400/0891B2/FFFFFF?text=100ft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert variants without duplicates
        foreach ($variants as $variant) {
            ProductVariant::firstOrCreate(
                ['sku' => $variant['sku']],
                $variant
            );
        }
    }
}